sudo: required
services:
        - docker

before_install:
        - docker build -t swarthofole/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true swarthofole/react-test npm test

after_succes:
        - docker build -t swarthofole/multi-client ./client 
        - docker build -t swarthofole/multi-nginx ./nginx
        - docker build -t swarthofole/multi-server ./server
        - docker build -t swarthofole/multi-worker ./worker
        - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
          #        - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
        - docker push swarthofole/multi-client
        - docker push swarthofole/multi-nginx
        - docker push swarthofole/multi-server
        - docker push swarthofole/multi-worker


